# 00. PyTorch Fundamentals — Solutions

### Overview & Objectives
* **Tensor Initialization:** Constructing deterministic and random multi-dimensional tensors.
* **Linear Algebra Operations:** Executing standard and batch matrix multiplications (`torch.matmul`, `@`) while managing inner/outer dimension constraints.
* **Statistical Aggregations:** Extracting global and axis-wise extrema (`torch.min`, `torch.max`) along with positional indices (`torch.argmin`, `torch.argmax`).
* **Dimension Manipulation:** Altering tensor dimensionality via `torch.squeeze` and `torch.unsqueeze` for dimension alignment.
* **Reproducibility & Hardware:** Setting seeds across CPU and CUDA (`torch.manual_seed`, `torch.cuda.manual_seed`) to ensure reproducible tensor generation on GPU.

-----------
-----------

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.1614, 0.4166, 0.8933, 0.5244, 0.0833, 0.8028, 0.3090],
        [0.1205, 0.2432, 0.8506, 0.0835, 0.7519, 0.0485, 0.1435],
        [0.6888, 0.1351, 0.6668, 0.6163, 0.4702, 0.1458, 0.1265],
        [0.2417, 0.9426, 0.4649, 0.5573, 0.8042, 0.7825, 0.0328],
        [0.9972, 0.4575, 0.5628, 0.5421, 0.9563, 0.1854, 0.8638],
        [0.9323, 0.4049, 0.6078, 0.1335, 0.7072, 0.1055, 0.9824],
        [0.9888, 0.3743, 0.9139, 0.0754, 0.5525, 0.8730, 0.6771]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor2 = torch.rand(1,7)
# Perform matrix multiplication 
mat_mul = tensor.mm(tensor2.T)
mat_mul, mat_mul.shape

(tensor([[1.5660],
         [1.3179],
         [1.3735],
         [2.0617],
         [2.2690],
         [2.0223],
         [2.5375]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_A = torch.rand(7,7)
random_tensor_B = torch.rand(1,7)
# Matrix multiply tensors
mat_mul1 = random_tensor_A.mm(random_tensor_B.T)
mat_mul1, mat_mul1.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device: ", device)
# Create two random tensors on GPU
tensor1_on_cpu = torch.rand(2,3)
tensor2_on_cpu = torch.rand(2,3)
tensor1_on_gpu = tensor1_on_cpu.to(device)
tensor2_on_gpu = tensor2_on_cpu.to(device)
tensor1_on_gpu, tensor2_on_gpu

Device:  cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
res = tensor1_on_gpu @ tensor2_on_gpu.T
res, res.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
print(torch.max(res))
# Find min
print(torch.min(res))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
print(torch.argmax(res))

# Find arg min
print(torch.argmin(res))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [16]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()

# Print out tensors and their shapes
random_tensor, random_tensor.shape, random_tensor_squeezed, random_tensor_squeezed.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))