# 00. PyTorch Fundamentals & Deep Learning Foundations

### Overview & Core Concepts
* **Machine Learning vs. Deep Learning:** Traditional rule-based programming vs. probabilistic pattern extraction; structured tabular models (XGBoost, Random Forest) vs. deep neural representations on unstructured data (text, vision, audio).
* **Neural Network Mechanics:** Numerical encoding of inputs $\rightarrow$ hidden layer feature learning (linear & non-linear transformations) $\rightarrow$ representation output decoding.
* **Tensors & Tensor Operations:** Creation (scalars, vectors, matrices, n-dimensional tensors), random initialization, range indexing, metadata inspection (`shape`, `dtype`, `device`), and core math (element-wise ops, matrix multiplication rules).
* **Dimensional Manipulation:** Reshaping, viewing, stacking, squeezing, unsqueezing, and permuting tensor dimensions.
* **Interoperability & Hardware:** Bridging PyTorch tensors with NumPy, seed-based reproducibility (`torch.manual_seed`), and device-agnostic acceleration switching between `CPU` and `CUDA` (GPU).

------------
------------

# PyTorch for Deep Learning

* Machine Learning is turning things(data) into numbers and finding patterns in those numbers.
* Deep Learning is subset of Machine Learning which is a subset of Artificial Intelligence.

TRADITIONAL PROGRAMMING: INPUTS -> RULES -> OUTPUT
MACHINE LEARNING ALGORITHM: INPUTS(features) & OUTPUT(labels) -> FIGURES OUT RELATION

1. Why use ML and DL?
   - Problems with long list of rules (traditional approach listing and managing all rules is too much impossible in case of complex problems but ML/DL can help) 
   - Continuously Changing environments - DL can adapt to new scenarios
   - Discovering insights within large collections of data - Traditional way is too cumbersome.
2. What DL isnt good for?
   - When we need explainability(the patterns of learning interpreting them)
   - When traditional rule based system is better option
   - When errors are unacceptable(DL models are probabilistic)
   - When we dont have much data.
3. ML vs DL:
   - ML operates on structures data
   - Algos like XGBoost
   - Random Forest, Graient Boostted Models, Naive Bayes, Nearest neighbour, Support Vector Machines etc. (shallow algos)
   - vs
   - DL operates on unstructured data like text, images, audio, videos etc.
   - Uses Neural Networks
   - Neural Networks, Fully Connected NN, Convolutional NN, Recurrent NN, Transformers (deeper algos as many layers)
     * Depending how we represent our problems, many algorithms can be used for both structured data and unstructured data.
4. What is NN:
   - Inputs -> Numberical Encoding(converting data into numbers) -> Learns representation(patterns/features/weights)(passing though a NN) -> Representation outputs(numberical output) -> Output(human understandable output)
5. Anantomy of NN:
   INPUT LAYER(data goes in here) -> HIDDEN LAYER(learns patterns in data) -> OUTPUT LAYER(outputs learned representation or prediction probabilities)
    * Each layer is usually a combination of linear(straight line) and/or non-linear(non-straight line) functions.
   
   *Note:* "Patterns" is an arbitrary term, "embeddings", "weights", "feature representation", "feature vectors" all referring to the same things.

7. Types of Learning:
   a. Supervised Learing(data and labels)
   b. Unsupervised & Self-Supervised Learning(data and no labels)
   c. Transfer Learning(transfers patterns from one model to another)
   d. Reinforcement Learning(Rewards and Punishment)
8. What DL is actually used for?
   - Recommendation Engines
   - Translation
   - Speech Recognition(sequence to sequence - seq2seq)
   - Computer Vision 
   - Natural Language Processing(spam classification email)
   - Classification/Regression

1. What is PyTorch?
   - Most popular DL framework(for research).
   - Writes fast DL code in Python(able to run on a GPU/many GPUs)
   - Able to access many pre-built DL models(Torch Hub/torchvision.models)
   - Whole stack: preprocess data, model data, deploy model in your application/cloud
   - Originally designed and used in-house by Meta(now open source and used by Tesla, Microsoft, OpenAI)
   - It helps run ML/DL code accelerated on a GPU
2. What is GPU/TPU?
   - CUDA is a paralell computing platform and API(application programming interface) that allows software to ise certain types of GPU for general purpose processing.
   - GPU(Graphics Processing Unit): fast at crunching numbers originally aimed for video games graphics rendering.
   - TPU(Tensor Processing Unit)

3. What is a tensor?
   - Tensor is a multi-dimensional array of numbers that serves as the fundamental data structure for represennting and manipulating data in frameworks like TensorFlow and PyTorch.

## PyTorch WorkFlow
1. Getting data ready(turn into tensors)
2. Build or pick a pretrained model(to suit our problem) ->
   -> 2.1. Pick a loss function & optimizer
   -> 2.2. Build a training loop -> 2.
3. Fit the model to the data and make a prediction
4. Evaluate the model
5. Improve through experimentation
6. Save and reload your trained model

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
torch.__version__

'2.10.0+cpu'

- An image of say 224x224 pixels will have a tensor like [3,224,224] for like [color_channels, height, width]. 3 Color channels (R,G,B)

# Introduction to Tensors
## Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
print(type(scalar))
scalar

<class 'torch.Tensor'>


tensor(7)

In [3]:
print(scalar.ndim) #returns the dimension of scalar(here)
print(scalar.shape)

0
torch.Size([])


In [4]:
scalar.item() #returns the actual data stored in scalar

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
print(vector.ndim) #no. of square brackets
# print(vector.item()) #it will result in an Runtime Error: a Tensor with 2 elements cant be converted into a scalar
print(vector.shape) #no. of elements

1
torch.Size([2])


## Scalar, Vector, Matrix and Tensor
-  S = 10 (scalar)
- V = [1, 2] (vector)
- M = [[1, 2], [3, 4]] (matrix)
- T = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] (3D tensor)

In [7]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [9]:
print(MATRIX[1])
print(MATRIX[0][1]) #here MATRIX[1][2] will give out of bounds error as dimension of matrix is 2x2 and indexing starts at 0.

tensor([ 9, 10])
tensor(8)


In [10]:
# TENSOR(n-dimensional array of numbers while matrix is a 2-D array of numbers)
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR #usually MATRIX and TENSORS are nomenclature in written in capital(usually to avoid confusion between scalars/vectors and tensors/matrices)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])
print(TENSOR[0][0])
print(TENSOR[0][0][0])
# its a single tensor so we get IndexError: index 1 is out of bounds for dimension 0 with size 1 as shape of tensor is 1x3x3

3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([1, 2, 3])
tensor(1)


In [12]:
#Example tensor2
TENSOR2 = torch.tensor([
                         [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                         [[3, 4, 6], [9, 0, 1], [4, 3, 7]]
])
TENSOR2

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[3, 4, 6],
         [9, 0, 1],
         [4, 3, 7]]])

In [13]:
print(TENSOR2.ndim)
print(TENSOR2.shape)
print(TENSOR2[1])
print(TENSOR2[0][1])
print(TENSOR2[1][0][1])

3
torch.Size([2, 3, 3])
tensor([[3, 4, 6],
        [9, 0, 1],
        [4, 3, 7]])
tensor([3, 6, 9])
tensor(4)


In [14]:
#Example Tensor3
TENSOR3 = torch.tensor([
                        [
                           [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
                           [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
                           [[29, 30, 31], [32, 33, 34], [35, 36, 37]] 
                        ],
                        [
                           [[41, 42, 43], [44, 45, 46], [47, 48, 49]],
                           [[50, 51, 52], [53, 54, 55], [56, 57, 58]],
                           [[59, 60, 61], [62, 63, 64], [65, 66, 67]] 
                        ],
                        [
                           [[71, 72, 73], [74, 75, 76], [77, 78, 79]],
                           [[80, 81, 82], [83, 84, 85], [86, 87, 88]],
                           [[89, 90, 91], [92, 93, 94], [95, 96, 97]] 
                        ]        
])
TENSOR3

tensor([[[[11, 12, 13],
          [14, 15, 16],
          [17, 18, 19]],

         [[20, 21, 22],
          [23, 24, 25],
          [26, 27, 28]],

         [[29, 30, 31],
          [32, 33, 34],
          [35, 36, 37]]],


        [[[41, 42, 43],
          [44, 45, 46],
          [47, 48, 49]],

         [[50, 51, 52],
          [53, 54, 55],
          [56, 57, 58]],

         [[59, 60, 61],
          [62, 63, 64],
          [65, 66, 67]]],


        [[[71, 72, 73],
          [74, 75, 76],
          [77, 78, 79]],

         [[80, 81, 82],
          [83, 84, 85],
          [86, 87, 88]],

         [[89, 90, 91],
          [92, 93, 94],
          [95, 96, 97]]]])

In [15]:
print(TENSOR3.ndim)
print(TENSOR3.shape)
print(TENSOR3[1])
print(TENSOR3[0][1])
print(TENSOR3[1][0][1])
print(TENSOR3[1][2][0][1])

4
torch.Size([3, 3, 3, 3])
tensor([[[41, 42, 43],
         [44, 45, 46],
         [47, 48, 49]],

        [[50, 51, 52],
         [53, 54, 55],
         [56, 57, 58]],

        [[59, 60, 61],
         [62, 63, 64],
         [65, 66, 67]]])
tensor([[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]])
tensor([44, 45, 46])
tensor(60)


---

## Random Tensors
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at the data -> update random numbers`

In [16]:
# Random Tensors
random_tensor = torch.rand(5,5,5)
random_tensor, random_tensor.shape, random_tensor.ndim, random_tensor.dtype

(tensor([[[0.9940, 0.8683, 0.1546, 0.1813, 0.0473],
          [0.8376, 0.6244, 0.7724, 0.9936, 0.4286],
          [0.3534, 0.9057, 0.9639, 0.6773, 0.1196],
          [0.4718, 0.1580, 0.8221, 0.6593, 0.6869],
          [0.2984, 0.3230, 0.4136, 0.4815, 0.1144]],
 
         [[0.5515, 0.5407, 0.8760, 0.7428, 0.8280],
          [0.9140, 0.4905, 0.8787, 0.5693, 0.7569],
          [0.6695, 0.0123, 0.4610, 0.8048, 0.7928],
          [0.3451, 0.6691, 0.5915, 0.1269, 0.1442],
          [0.3948, 0.5384, 0.5940, 0.9145, 0.6983]],
 
         [[0.7833, 0.1027, 0.5769, 0.1651, 0.5645],
          [0.8311, 0.3986, 0.3798, 0.7172, 0.0962],
          [0.8917, 0.1696, 0.8910, 0.9203, 0.3500],
          [0.9402, 0.9428, 0.1177, 0.6792, 0.9668],
          [0.1598, 0.8092, 0.9251, 0.9001, 0.7954]],
 
         [[0.5193, 0.7949, 0.4211, 0.6699, 0.6792],
          [0.8849, 0.6484, 0.3488, 0.1200, 0.2752],
          [0.7389, 0.4193, 0.8521, 0.6781, 0.6564],
          [0.1747, 0.0174, 0.5491, 0.7408, 0.3366],
   

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width, color channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim, random_image_size_tensor.dtype

(torch.Size([224, 224, 3]), 3, torch.float32)

In [18]:
random_tensor_test = torch.rand(3,4)
#Creating tensors with all zeros
print(random_tensor_test)
zeros = torch.zeros(3,4)
zeros, zeros.ndim, zeros.ndim, zeros.shape

tensor([[0.3764, 0.0315, 0.7012, 0.4179],
        [0.0093, 0.2426, 0.2730, 0.6403],
        [0.3243, 0.3407, 0.7972, 0.0834]])


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2,
 2,
 torch.Size([3, 4]))

In [19]:
zeros*random_tensor_test

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
random_tensor_test2 = torch.rand(4,4)
#Creating tensors with all zeros
ones = torch.ones(4,4)
random_tensor_test2, ones, ones.ndim, ones.ndim, ones.shape, ones.dtype

(tensor([[0.5746, 0.6959, 0.7299, 0.2048],
         [0.5098, 0.8547, 0.4180, 0.2152],
         [0.3056, 0.0790, 0.3601, 0.5337],
         [0.2463, 0.6640, 0.7489, 0.9875]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 2,
 2,
 torch.Size([4, 4]),
 torch.float32)

In [21]:
ones*random_tensor_test2

tensor([[0.5746, 0.6959, 0.7299, 0.2048],
        [0.5098, 0.8547, 0.4180, 0.2152],
        [0.3056, 0.0790, 0.3601, 0.5337],
        [0.2463, 0.6640, 0.7489, 0.9875]])

---

## Creating a range of Tensor and tensors-like

In [22]:
one_to_ten = torch.arange(start = 0, end = 10, step = 2) #arange is used to define the range
one_to_ten

tensor([0, 2, 4, 6, 8])

In [30]:
#Creating tensors like
five_zeros = torch.zeros_like(input = one_to_ten)
five_ones = torch.ones_like(input = one_to_ten)
five_zeros, five_ones

(tensor([0, 0, 0, 0, 0]), tensor([1, 1, 1, 1, 1]))

---

# Tensor Data Types

3 most common errors in PyTorch
1. Tensors aren't of right datatype
2. Tensors not right shape
3. Tensors not on right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)
print(float_32_tensor, float_32_tensor.dtype) #float32 is the default datatype
float_16_tensor = torch.tensor([2.0, 4.0, 6.0], 
                               dtype = torch.float16, # what datatype is the tensor (float16-half precision, float32-single precision, float64- double precision)
                               device = None, #device on which tensor is allocated(cpu, cuda(gpu) are more common)
                               requires_grad = False #whether or not to track gradients with this tensor to track opertions(e.g use case: backpropagation)
                              )
print(float_16_tensor, float_16_tensor.dtype)
float_64_tensor = torch.tensor([1.0, 2.0, 6.0], dtype = torch.float64, device = None, requires_grad = True)
print(float_64_tensor, float_64_tensor.dtype, float_64_tensor.device) #device is cpu by default

tensor([3., 6., 9.]) torch.float32
tensor([2., 4., 6.], dtype=torch.float16) torch.float16
tensor([1., 2., 6.], dtype=torch.float64, requires_grad=True) torch.float64 cpu


In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
ans = float_16_tensor * float_32_tensor #float_16_tensor is now same as float_32_tensor so multiplication result is like this
ans, ans.dtype, ans.shape

(tensor([ 9., 36., 81.]), torch.float32, torch.Size([3]))

In [27]:
#example 2
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [28]:
ans * int_32_tensor, (ans * int_32_tensor).dtype
# TYPE PROMOTION(UpCasting of datatype from int64 to float32 even if 64 bits as float always wins, else in int32 vs int64, int64 wins)

(tensor([ 27., 216., 729.]), torch.float32)

---

## Getting information from tensors
(Problems)
1. Tensors not the right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [29]:
some_random_tensor = torch.rand(4,4)
some_random_tensor, some_random_tensor.dtype, some_random_tensor.shape, some_random_tensor.device

(tensor([[0.8172, 0.8793, 0.6983, 0.5729],
         [0.7295, 0.2907, 0.0902, 0.9336],
         [0.7742, 0.6173, 0.7776, 0.6993],
         [0.8679, 0.8318, 0.7573, 0.2163]]),
 torch.float32,
 torch.Size([4, 4]),
 device(type='cpu'))

---

# Manipulating Tensors(tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [31]:
# Addition with a tensor
tensor1 = torch.tensor([1,2,3])
print(tensor1 + 10) #adds 10 across all elements
tensor2 = torch.tensor([4,5,6])
print(tensor1 + tensor2) #adds elements of 2nd tensor with 1st tensor with respective element

tensor([11, 12, 13])
tensor([5, 7, 9])


In [32]:
# Multiplication with a tensor
print(tensor1 * 10) # multiplies 10 across all elements
print(tensor1 * tensor2) # multiplies elements of 2nd tensor with 1st tensor with respective element

tensor([10, 20, 30])
tensor([ 4, 10, 18])


In [33]:
# Subtraction with a tensor
print(tensor1 - 10) # subtracts 10 across all elements
print(tensor1 - tensor2) # subtracts elements of 2nd tensor from 1st tensor with respective element

tensor([-9, -8, -7])
tensor([-3, -3, -3])


In [34]:
# Addition with a tensor
print(tensor1 / 10) # divides 10 across all elements
print(tensor1 / tensor2) # divides elements of 1st tensor by 2nd tensor with respective element

tensor([0.1000, 0.2000, 0.3000])
tensor([0.2500, 0.4000, 0.5000])


In [35]:
# PyTorch in-built funcitons
print(torch.mul(tensor2, 10))
print(torch.div(tensor2, 5))
print(torch.add(tensor1, 2))
print(torch.sub(tensor1, 3))

tensor([40, 50, 60])
tensor([0.8000, 1.0000, 1.2000])
tensor([3, 4, 5])
tensor([-2, -1,  0])


## Matrix Multiplication
(Dot Product)

Rules for performing Matrix Multiplication:
1. The **inner dimension** must match:
   - for compatibility of matrix multiplication of `(a,b) @ (c,d)` *b must be equal to c*
(@ symbol is for matrix multiplication)
2. The resulting matrix has the shape of the **outer dimension**:
   - `(a,b) @ (b,c)` will result in a matrix of `(a,c)`

In [36]:
# Element wise multiplication
print(tensor1, "*", tensor2)
tensor1*tensor2

tensor([1, 2, 3]) * tensor([4, 5, 6])


tensor([ 4, 10, 18])

In [37]:
# Matrix Multiplication
torch.matmul(tensor1, tensor2) #tensor2 is transposed (1*4+2*5+3*6)

tensor(32)

In [38]:
import time
# Time difference between manual matrix multiplication vs using torch,matmul()

# Create 2 large tensors
size = 100000
tensorA = torch.rand(size)
tensorB = torch.rand(size)

#----Method 1: Manual loop----
start = time.time()
value = 0
for i in range(size):
    value += tensorA[i] * tensorB[i]
end = time.time()
print(f"Time spent in manual method is {end-start} seconds")

#----Method 2: torch.dot/torch.matmul----
%timeit torch.dot(tensorA, tensorB)

# torchtime = %timeit -o torch.dot(tensorA, tensorB)
# print(f"Time spent in torch method is {torchtime}")

# %%timeit
# value = 0
# for i in range(len(tensor1)):
#     value += tensor1[i] * tensor2[i]
# print(value)

#The massive time difference is due to 
# 1. Interpreted Overhead
#     - check the type, check the bounds(is the index i is in the array), fetch the next instruction
# 2. Vectorization(SIMD-Single Instruction Multiple Data)
#     - instead of 1+1 then 2+2, it does [1,2,3] + [1,2,3] in a single "blink"
# 3. Memory Locality and Caching
#     - manual loops look around in memory for python ojects which are scattered everywhere, causes "cache miss" so CPU have to wait
#     - while tensor are stored in single block of memory so no delay

Time spent in manual method is 0.9383869171142578 seconds
13 µs ± 328 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
# Rule1: matrix multiplication inner dimensions must match

# torch.matmul(torch.rand(3,2), torch.rand(3,2))
# this gives "RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)""

# Rule2: Result is matrix of outer dimensions
tensor_a = torch.rand(3,2)
tensor_b = torch.rand(2,3)
tensor_res = torch.matmul(tensor_a, tensor_b)
tensor_res, tensor_res.shape 
# 3x3 is the outer dimension

(tensor([[0.4576, 0.7458, 0.8721],
         [0.1479, 0.2409, 0.2810],
         [0.4792, 0.7672, 0.8294]]),
 torch.Size([3, 3]))

## One of the most common errors in Deep Learning: Shape Errors

In [40]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
#torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
torch.mm(tensor_A, tensor_B.T) #Transpose to make inner dimension match

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [41]:
tensor_B, tensor_B.T, tensor_B.shape, tensor_B.T.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A **transpose** switches the axes or dimensions of a given tensor.

---

## Finding the min, max, mean, sum etc. (Tensor Aggregation)

In [42]:
x = torch.arange(0, 100, 10) #(start,end,step)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [43]:
print(torch.max(x), x.max()) #finding max
print(torch.min(x), x.min()) #finding min

# print(torch.mean(x), x.mean()) #mean #it will lead to an runtime error that dtype must be float or complex
print(torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()) #finding mean
print(torch.sum(x), x.sum()) #finding sum

tensor(90) tensor(90)
tensor(0) tensor(0)
tensor(45.) tensor(45.)
tensor(450) tensor(450)


# Finding the positional min and max 

In [44]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
print(x.argmin()) #prints the index of the min value element in tensor
print(x.argmax()) #prints the index of the max value element in tensor

tensor(0)
tensor(9)


In [46]:
x[0], x[9]

(tensor(0), tensor(90))

## Reshaping, Stacking, Squeezing and Unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape(should be compatible to the original size)
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions from a tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [55]:
# Create a tensor
x = torch.arange(1,10)
x, x.shape, x.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), 1)

### Reshaping

In [56]:
# Reshaping
# Add an extra dimension
# x_reshaped = x.reshape(1,7) 
##It will produce an RuntimeError: shape '[1, 7]' is invalid for input of size 9; as we are trying to squeeze 9 elements(original) to 1x7(7 elements)
## (1,8), (1,10), (2,7) all invalid; only(1,9) and (9,1) valid

x_reshaped = x.reshape(1,9)
print(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(9,1)
print(x_reshaped, x_reshaped.shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([9, 1])


In [57]:
x1 = torch.arange(1,13)
print(x1, x1.shape)
x1_reshaped = x1.reshape(2,6)
print("(2x6): ", x1_reshaped, x1_reshaped.shape)
x1_reshaped = x1.reshape(6,2)
print("(6x2): ", x1_reshaped, x1_reshaped.shape)
x1_reshaped = x1.reshape(3,4)
print("(3x4): ", x1_reshaped, x1_reshaped.shape)
x1_reshaped = x1.reshape(4,3)
print("(4x3): ", x1_reshaped, x1_reshaped.shape)
x1_reshaped = x1.reshape(12,1)
print("(12x1): ", x1_reshaped, x1_reshaped.shape)
x1_reshaped = x1.reshape(1,12)
print("(1x12): ", x1_reshaped, x1_reshaped.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]) torch.Size([12])
(2x6):  tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]) torch.Size([2, 6])
(6x2):  tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]) torch.Size([6, 2])
(3x4):  tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) torch.Size([3, 4])
(4x3):  tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) torch.Size([4, 3])
(12x1):  tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]) torch.Size([12, 1])
(1x12):  tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]) torch.Size([1, 12])


### View

In [58]:
# View(changing the view)
z = x.view(1,9) #here (1,9) isnt the range but the matrix size and (9,1) also possible
z,x

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

- Changing z changes x because a view of a tensor shares the same memory as the original input.(as shown in below cell)
- The difference between view and reshape is:
  * "View" is used if tensor is contiguous(continuous memory location), while
  * "Reshape" is used for both contiguous and non-contiguous tensors. If contiguous same output as view else
    if non-contiguous then it automatically creates a copy to make the tensor contiguous. Hence view is faster due to no copying data      overhead.
- Contiguous/not can be chacked by (x.is_contiguous())

In [64]:
z[:, 0] = 5 #[:,5] means all rows first column, in case of (9x1) every row 0th element will be 5
z, x, x.is_contiguous(), x.T.is_contiguous() #x.mT is matrix transpose same as x.T for tensors other than dimension 2

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]),
 True,
 True)

### Stack
torch.cat() just concatenate the elements without chaging the dimension of tensor(end-to-end long strip(36 numbers) of paper taped(each paper strip contains 9 numbers))

while,

torch.stack() adds a new dimensions and create a grid(one paper strip(9 numbers) placed on top of another)

- vstack(dim=0)
- hstack(dim=1)

In [67]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0) #default dimension value is 0. #((9) to (4x9))
x_stacked
# Stack takes a list of tensors and concatenates a sequence of tensors along a new dimension. All tensors need to be of the same size.

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [68]:
x_stacked = torch.stack([x, x, x, x], dim = 1) # ((9) to (9x4))
x_stacked
# On using dim = 2; IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2) 
# due to compatibility with x's original shape(1,9)

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

Here x dimension is 1, 
so when we stack 4 x's [x,x,x,x] using 
dim=0 (stacking as rows): take 4 as first number to insert a new dimension i.e from [9] convert it to [4x9]
dim=1 (stacking as columns): take 4 as second number to insert a new dimension i.e from [9] convert it to [9x4]

in 9x1 there will be two dimensions so dim will go from 0,1,2 and if dim =0 then final result after stack is (4,9,1), dim=1 then(9,4,1) and dim=2 then (9,1,4); coz dim decides which position 4 to add to to make new dimension 3rd

---

torch.cat() if we use a 9x1 tensor (add no dimension)
- dim = 0 (glue them end-to-end vertically) ; result shape: (36,1) i.e (9+9+9+9)x1
- dim = 1 (glue them side-by-side horizontally); result shape: (9,4) i.e 9x(1+1+1+1)

while
torch.stack() (adds a dimenision)
- dim = 0 results in (4,9,1)
- dim = 1 results in (9,4,1)
- dim = 2 results in (9,1,4)

---

### Squeeze and Unsqueeze

In [69]:
# Squeeze(removes all single diensions from a target tensor)
x_old = torch.rand(1,3,2,1)
x_new = x_old.squeeze()
print("x_old: ", x_old, x_old.shape, x_old.ndim)
print("x_new: ", x_new, x_new.shape, x_new.ndim)

# Unsqueeze(adds single dimenion to a target tensor at a specific dim(dimension))
x_new2 = x_new.unsqueeze(dim = 0)
print("x_new2: ", x_new2, x_new2.shape, x_new2.ndim)
x_new2 = x_new.unsqueeze(dim = 1)
print("x_new2: ", x_new2, x_new2.shape, x_new2.ndim)
x_new2 = x_new.unsqueeze(dim = 2) #originally 4 dimensions squeezed to 2 then unsqueezed to 3 so dim range is [0,1,2] and 3 onwards give error
print("x_new2: ", x_new2, x_new2.shape, x_new2.ndim)

x_old:  tensor([[[[0.1969],
          [0.5144]],

         [[0.6165],
          [0.2455]],

         [[0.0503],
          [0.0150]]]]) torch.Size([1, 3, 2, 1]) 4
x_new:  tensor([[0.1969, 0.5144],
        [0.6165, 0.2455],
        [0.0503, 0.0150]]) torch.Size([3, 2]) 2
x_new2:  tensor([[[0.1969, 0.5144],
         [0.6165, 0.2455],
         [0.0503, 0.0150]]]) torch.Size([1, 3, 2]) 3
x_new2:  tensor([[[0.1969, 0.5144]],

        [[0.6165, 0.2455]],

        [[0.0503, 0.0150]]]) torch.Size([3, 1, 2]) 3
x_new2:  tensor([[[0.1969],
         [0.5144]],

        [[0.6165],
         [0.2455]],

        [[0.0503],
         [0.0150]]]) torch.Size([3, 2, 1]) 3


### Permute

In [70]:
# torch.permute - rearranges the dimensions of a target in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, colour_channels]
x_permuted = x_original.permute(2,0,1) # the position change is written here like at 0th-2 , 1st-0 and 2nd-1
#shifts axis 0->1, 1->2, 2->0 (height moves to 1 index, width to 2 index and colour to 0 index)
x_permuted.shape #[colour_channels, height, width]
#The data in both x_original and x_permuted tensor is same only its viewed from a different point of view, and both share the same memory

torch.Size([3, 224, 224])

In [71]:
x_original[0,0,0] = 43244
x_original[0,0,0], x_permuted[0,0,0]

(tensor(43244.), tensor(43244.))

## Indexing(selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [72]:
# Create a tensor
x_ind = torch.arange(1,28).reshape(3,3,3)
x_ind, x_ind.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]),
 torch.Size([3, 3, 3]))

In [73]:
x_ind[0], x_ind[0][0], x_ind[0][0][0] #x_ind[0][0] is same as x_ind[00]
#dim=0    #dim=1       #dim=2(innermost bracket)

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [74]:
x_ind[0][1][1] #[1][1][1] will give out of bounds error as 1st dimension is 1 (1x3x3)

tensor(5)

In [75]:
# We can also use ":" to select "all" of a target dimension

# (Get all values of 0th dimension and 0th element from that(dimension 1 that's remaining))
# Keep all rows(dim0), but only take first slice of second dimension(dim1). This collapses the middle dimension, leavind a 2D result
print(x_ind[:,0])

# (Get all values of 0th and 1st dimension but only index 1 of second dimension(innermost dimension))
# Keep everything from the first two dimensions, but only grab the second element of the innermost axis
print(x_ind[:, :, 1])

# (Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension)
print(x_ind[:,1,1])

# (Get index 0 of 0th and 1st dimension and all values of 2nd dimension)
print(x_ind[0,0,:])

# Index on x_ind to return 9
print(x_ind[0,2,2])
# Index on x_ind to return [3,6,9]
print(x_ind[0,:,2])

tensor([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]])
tensor([[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]])
tensor([ 5, 14, 23])
tensor([1, 2, 3])
tensor(9)
tensor([3, 6, 9])


In [76]:
# Example 2
images = torch.rand(2,3,4,4) #(N,C,H,W) #no of images, colour channels, height, width
print("images: ", images)

# Want all of N, only index 0 of C, all of H, all of W
red_channels = images[:, 0, :, :] #o/p:(2x4x4)
print("red_channels: ", red_channels)

# Want index 0 of N, and everythig else
first_image = images[0, :, :, :]     #if it was [:, :, :, 0] we could also write [..., 0], even 10D also same
print("first_image: ", first_image) #o/p: (3x4x4)

# Want center pixel [2,2] of every image
pixels = images[:, :, 2, 2] #o/p: 2x3
print("pixels: ", pixels)

images:  tensor([[[[0.9368, 0.7927, 0.3365, 0.6817],
          [0.8091, 0.0163, 0.8241, 0.8684],
          [0.2588, 0.1434, 0.5175, 0.1301],
          [0.1332, 0.6881, 0.7094, 0.9871]],

         [[0.3653, 0.2374, 0.0424, 0.0324],
          [0.8589, 0.4985, 0.5122, 0.5689],
          [0.9453, 0.1699, 0.3388, 0.9171],
          [0.2742, 0.3560, 0.7318, 0.1976]],

         [[0.8037, 0.2104, 0.0388, 0.1706],
          [0.5956, 0.3859, 0.2266, 0.5085],
          [0.8437, 0.1485, 0.1678, 0.8514],
          [0.9212, 0.7271, 0.6067, 0.3959]]],


        [[[0.0984, 0.1809, 0.7590, 0.7878],
          [0.6759, 0.8306, 0.4529, 0.9257],
          [0.1191, 0.1584, 0.7311, 0.9538],
          [0.1869, 0.0172, 0.2758, 0.9906]],

         [[0.9221, 0.1722, 0.5640, 0.2510],
          [0.5458, 0.2024, 0.4931, 0.0922],
          [0.6015, 0.4688, 0.5294, 0.5809],
          [0.1178, 0.7894, 0.7385, 0.4943]],

         [[0.0263, 0.7385, 0.1131, 0.0495],
          [0.4871, 0.4912, 0.7284, 0.5039],
          [

---

## PyTorch Tensors & NumPy

#### Numpy is a popular scientific Python numerical computing library. And because of this, PyTorch has functionality to interact with it.

- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray` (and change this into a torch tensor)
- PyTorch tensor to NumPy -> `torch.Tensor.numpy()`

In [78]:
## Numpy array to tensor
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array) #.type(float32) can also be used to change from default numpy dtype to our requirement
array, tensor
# warning: when converting from numpy -> pytorch, pytorch relects numpy's default datatype of float64 unless specified otherwise

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [79]:
array.dtype #array default datatype is float64

dtype('float64')

In [80]:
torch.arange(1.0, 10.0).dtype #but torch tensor default datatype is float32

torch.float32

In [81]:
# Changing the value of array, what will happen to tensor?
array = array  + 1
array, tensor
#changing the value of array have no effect on tensor as they are different memory locations

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [86]:
## Tensor to NumPy array
tensor = torch.ones(9)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.dtype
#Note: here on conversion dtype is same as original tensor default i.e float32
# In both cases numpy -> tensor or vice-versa the original datatype prevails

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [87]:
# Changing the value of tensor, what happens to 'numpy_tensor'
tensor = tensor + 1
tensor, numpy_tensor
# changing the tensor have no affect on the numpy_tensor as both are different memory locations

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## PyTorch Reproducability
#### (trying to take randomness out of random)

- In short how a Neural Network learns:
  `start with random numbers -> tensor operations -> update random numbers to try to make them better representations of the data -> again -> again -> again ...`

- But we might want some less randomness(like when sharing our work with someone)
- To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
- Essentially what the random seed does is "flavour" the randomness.

- What computer basically does is pseudorandomness or generative randomness but random seed flavours that randomness

In [88]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7018, 0.3605, 0.5392, 0.4830],
        [0.8366, 0.2966, 0.8215, 0.5241],
        [0.0549, 0.1334, 0.2715, 0.9187]])
tensor([[0.0788, 0.9505, 0.7186, 0.0596],
        [0.8805, 0.2292, 0.8972, 0.6064],
        [0.4946, 0.4539, 0.9713, 0.3832]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
# Random but reproducable tensors
# Set the random seed(this number can be anything)
# RANDOM_SEED = 42
# torch.manual_seed(RANDOM_SEED)
# random_tensor_C = torch.rand(3,4)
# random_tensor_D = torch.rand(3,4)
# print(random_tensor_C)
# print(random_tensor_D)
# print(random_tensor_C == random_tensor_D)

# this will result in false values all as seed is set on only C and not D (if we use torch.manual_seed(RANDOM_SEED) at top it 
#   might work(only 1st time after restarting notebook but C!=D; actually they arent equal but REPRODUCABILITY is executed) 
#   but we have to use it every time we create a random tensor(block))
# this every time creates the same random numbers from page 42(computers generate random numbers using PESUDO-RANDOM NUMBER GENERATOR(PRNG))

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
# We must reset the seed before EVERY random operation if we want those specific operations to result in identical tensors.

#RANDOM_SEED = 77 #it will give all false results
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

# We must reset the seed before EVERY random operation if we want those specific operations to result in identical tensors.
#after random seed if we share our work to someone then the person will get the same result as us.
# seed = 42 means open page 42(it can also be 0,1,7,999, etc anything)
# for GPU usage; torch.cuda.manual_seed_all(RANDOM_SEED) is better than torch.manual_seed(RANDOM_SEED)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch objects on the GPUs (and making faster computations)

- GPUs = faster computation on numbers, thanks to CUDA + NVIDIA harddware + PyTorch working behind the scenes to make everything hunky dory(good).

#### Getting a GPU
1. Google Colab, Kaggle
2. Own GPU
3. Cloud Computing(AWS, Azure, GCP)

In [1]:
!nvidia-smi #using GPU P100

Wed May 13 16:57:04 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P100-PCIE-16GB           Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P0             26W /  250W |       0MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Check for GPU Access with PyTorch

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
# Setup device agnostic code(while running PyTorch code we might not have always access to a GPU, if there's a GPU available then we'll like to use it)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

- For PyTorch since its capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.
- E.g: Run on GPU if available, else default to CPU

In [3]:
# Count the number of GPU
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU
- The reason we want our tensors/models on the GPU is because using a GPU results in faster calculations.

In [4]:
# Create a tensor(By default tensor is on  CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU(if available) #Tensor.to(target device) is used for the purpose
tensor_on_gpu = tensor.to(device) #device here is the target device(gpu here as defined above)
tensor_on_gpu
# cuda:0 is the index of the GPU we are using(as we're using 1 so index is 0, in case of multiple different index will come)

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [11]:
# If tensor is on GPU, then it cant transform into NumPy
#tensor_on_gpu.numpy()
# it wil result in "TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first."

# copying tensor to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu, tensor_on_gpu

(array([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))